---
# Configure dropbear section
- name: Configure dropbear section
  ansible.builtin.include_tasks: dropbear.yml

# Apply changes and reload dropbear service
- name: Apply changes and reload dropbear
  uci:
    command: commit
  notify: Reload dropbear
